services:
  lb:
    image: ghcr.io/sergiotec/rinha-2026:latest
    command: ["/app/lb"]
    ports:
      - "9999:9999"
    environment:
      - LB_PORT=9999
      - LB_BACKENDS=/tmp/sockets/api1.sock,/tmp/sockets/api2.sock
    networks:
      - rinha
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '10MB'
    volumes:
      - sockets:/tmp/sockets

  api1:
    image: ghcr.io/sergiotec/rinha-2026:latest
    command: ["/app/api"]
    environment:
      - LISTEN_SOCKET=/tmp/sockets/api1.sock
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '165MB'
    volumes:
      - sockets:/tmp/sockets
    healthcheck:
      test: ["CMD", "bash", "-c", "test -S /tmp/sockets/api1.sock"]
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 20s

  api2:
    image: ghcr.io/sergiotec/rinha-2026:latest
    command: ["/app/api"]
    environment:
      - LISTEN_SOCKET=/tmp/sockets/api2.sock
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.40'
          memory: '165MB'
    volumes:
      - sockets:/tmp/sockets
    healthcheck:
      test: ["CMD", "bash", "-c", "test -S /tmp/sockets/api2.sock"]
      interval: 2s
      timeout: 1s
      retries: 30
      start_period: 20s

volumes:
  sockets:

networks:
  rinha:
    driver: bridge
