services:
  lb:
    image: nginx:alpine
    ports:
      - "9999:9999"
    command: >
      sh -c "echo 'events { worker_connections 4096; use epoll; multi_accept on; } http { upstream api_backend { server api1:9001; server api2:9002; keepalive 64; keepalive_requests 1000; keepalive_timeout 60s; } server { listen 9999; access_log off; location / { proxy_pass http://api_backend; proxy_http_version 1.1; proxy_set_header Connection \"\"; proxy_connect_timeout 2s; proxy_read_timeout 10s; proxy_send_timeout 10s; proxy_buffering off; } } }' > /tmp/nginx.conf && nginx -c /tmp/nginx.conf -g 'daemon off;'"
    networks:
      - rinha
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "10MB"

  api1:
    image: rinha-api:latest
    build: ./api
    environment:
      - PORT=9001
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"

  api2:
    image: rinha-api:latest
    build: ./api
    environment:
      - PORT=9002
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "165MB"

networks:
  rinha:
    driver: bridge
